In [ ]:
# prompt: import torch

import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
# prompt: if torch.cuda.is_available():

if torch.cuda.is_available():
  print(f"CUDA is available: {torch.cuda.get_device_name(0)}")
else:
  print("CUDA is not available")



CUDA is available: Tesla T4


Creating Tensor

In [ ]:
#using empty
a=torch.empty(2,3)
print(a)
print(type(a))

tensor([[5.1483e+22, 1.7753e+28, 1.8524e+28],
        [7.0004e+22, 1.9543e+08, 3.6073e+03]])
<class 'torch.Tensor'>


In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([[1,2,3],[20,30,40]])

tensor([[ 1,  2,  3],
        [20, 30, 40]])

In [ ]:
print("arange:",torch.arange(0,10,2))
print("linspace:",torch.linspace(0,10,10)) #evenly spaced
print("eye:",torch.eye(3)) #identity matrix
print("full:",torch.full((2,3),3)) #shape,value

arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
full: tensor([[3, 3, 3],
        [3, 3, 3]])


# Tensor datatype

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.23,3.36,6.5,4.25,8.65],dtype=torch.int64)

tensor([1, 2, 3, 6, 4, 8])

# Tensor shape,

In [ ]:
x=torch.tensor([[1,2,3],[20,30,40]])
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


In [ ]:
torch.empty_like(x) #shape like x

tensor([[0, 0, 0],
        [0, 1, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

Scaler operation

In [ ]:
((((((x+4)-2)*5)/100)%3)**5)

tensor([[7.5938e-05, 3.2000e-04, 9.7656e-04],
        [1.6105e+00, 1.0486e+01, 4.0841e+01]])

# Element-wise Operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print((((((a+b)-b)*a)/10*b)**a)%b)

tensor([[0.2548, 0.2379, 0.3401],
        [0.0605, 0.0659, 0.0711]])


In [ ]:
c=torch.tensor([-1,2,-3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([ 1, -2,  3,  4])

In [ ]:
d=torch.tensor([1.2,3,.09,3.4567])

In [ ]:
torch.round(d)

tensor([1., 3., 0., 3.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 1., 4.])

In [ ]:
torch.floor(d)

tensor([1., 3., 0., 3.])

In [ ]:
torch.clamp(d,min=2,max=3)

tensor([2., 3., 2., 3.])

Reduction Operation

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10)
print(e)


tensor([[7, 0, 0],
        [9, 5, 7]])


In [ ]:
#sum
print("total sum",torch.sum(e))
#col sum
print("column sum",torch.sum(e,dim=0))
#row sum
print("row sum" ,torch.sum(e,dim=1))

total sum tensor(28)
column sum tensor([16,  5,  7])
row sum tensor([ 7, 21])


In [ ]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.mean(f)

tensor(7.3333)

In [ ]:
print("column mean",torch.mean(f,dim=0))
print("row mean",torch.mean(f,dim=1))

column mean tensor([6., 7., 9.])
row mean tensor([7.6667, 7.0000])


In [ ]:
torch.median(e)

tensor(5)

In [ ]:
print("max",torch.max(e))
print("min",torch.min(e))
print("product",torch.prod(e))
print("variance",torch.var(f))
print("standard deviation",torch.std(f))
print("argmax",torch.argmax(e)) #index or position of max element
print("argmin",torch.argmin(e))

max tensor(9)
min tensor(0)
product tensor(0)
variance tensor(3.8667)
standard deviation tensor(1.9664)
argmax tensor(3)
argmin tensor(1)


# Matrix operation

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[0, 7, 4],
        [7, 6, 8]])
tensor([[6, 3],
        [5, 0],
        [0, 0]])


In [ ]:
torch.matmul(f,g)

tensor([[35,  0],
        [72, 21]])

In [ ]:
v1=torch.tensor([1,2])
v2=torch.tensor([3,4])

torch.dot(v1,v2)

tensor(11)

In [ ]:
print(f)

tensor([[0, 7, 4],
        [7, 6, 8]])


In [ ]:
torch.transpose(f,0,1)

tensor([[0, 7],
        [7, 6],
        [4, 8]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(h)

tensor([[1., 3., 8.],
        [5., 7., 8.],
        [1., 4., 1.]])


In [ ]:
torch.det(h)

tensor(88.)

In [ ]:
torch.inverse(h)

tensor([[-0.2841,  0.3295, -0.3636],
        [ 0.0341, -0.0795,  0.3636],
        [ 0.1477, -0.0114, -0.0909]])

# Comparison

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[1, 2, 8],
        [4, 5, 4]])
tensor([[0, 0, 5],
        [2, 1, 9]])


In [ ]:
i>j

tensor([[ True,  True,  True],
        [ True,  True, False]])

In [ ]:
i<j

tensor([[False, False, False],
        [False, False,  True]])

In [ ]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [ ]:
i!=j

tensor([[True, True, True],
        [True, True, True]])

# Special Function

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10)

In [ ]:
torch.log(k)

tensor([[0.6931, 1.0986, 2.1972],
        [0.6931, 1.7918, 1.6094]])

In [ ]:
torch.exp(k)

tensor([[7.3891e+00, 2.0086e+01, 8.1031e+03],
        [7.3891e+00, 4.0343e+02, 1.4841e+02]])

In [ ]:
torch.sqrt(k)

tensor([[1.4142, 1.7321, 3.0000],
        [1.4142, 2.4495, 2.2361]])

In [ ]:
torch.sigmoid(k)

tensor([[0.8808, 0.9526, 0.9999],
        [0.8808, 0.9975, 0.9933]])

In [ ]:
k=k.to(dtype=torch.float32)

In [ ]:
torch.softmax(k,dim=0)

tensor([[0.5000, 0.0474, 0.9820],
        [0.5000, 0.9526, 0.0180]])

In [ ]:
torch.softmax(k,dim=1)

tensor([[9.0880e-04, 2.4704e-03, 9.9662e-01],
        [1.3213e-02, 7.2140e-01, 2.6539e-01]])

In [ ]:
torch.relu(k)

tensor([[2., 3., 9.],
        [2., 6., 5.]])

# Inplace Operations

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.1199, 0.2528, 0.1008],
        [0.4389, 0.2555, 0.2961]])
tensor([[0.8915, 0.4832, 0.9871],
        [0.6375, 0.2312, 0.0374]])


In [ ]:
m.add_(n)

tensor([[1.0114, 0.7359, 1.0879],
        [1.0764, 0.4867, 0.3335]])

In [ ]:
m

tensor([[1.0114, 0.7359, 1.0879],
        [1.0764, 0.4867, 0.3335]])

In [ ]:
n

tensor([[0.8915, 0.4832, 0.9871],
        [0.6375, 0.2312, 0.0374]])

In [ ]:
m.relu_()

tensor([[1.0114, 0.7359, 1.0879],
        [1.0764, 0.4867, 0.3335]])

In [ ]:
m

tensor([[1.0114, 0.7359, 1.0879],
        [1.0764, 0.4867, 0.3335]])

# COpy a tensor

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.4472, 0.2861, 0.9556],
        [0.0690, 0.5450, 0.9139]])

In [ ]:
b=a
b

tensor([[0.4472, 0.2861, 0.9556],
        [0.0690, 0.5450, 0.9139]])

It is not desirable as we make any change in "a" it will also affect in "b"

In [ ]:
print(id(a))
print(id(b))

137244299258928
137244299258928


In [ ]:
b=a.clone()
print(b)

tensor([[0.4472, 0.2861, 0.9556],
        [0.0690, 0.5450, 0.9139]])


In [ ]:
print(id(a))
print(id(b))

137244299258928
137244114975248


# Tensor Operation in GPU

In [ ]:
torch.cuda.is_available()

NameError: name 'torch' is not defined

In [ ]:
device=torch.device('cuda')

In [ ]:
torch.rand((2,3),device=device)

In [ ]:
a

In [ ]:
a.to(device)

In [ ]:
a+5

# Reshaping Tensor

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)
# its mandate while reshaping a tensor that old tensor shape multi must be equal to new

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.2653, 0.9519, 0.9242, 0.8035],
         [0.5154, 0.2229, 0.5836, 0.2085],
         [0.7629, 0.9498, 0.5456, 0.1532]],

        [[0.1224, 0.2850, 0.6559, 0.8262],
         [0.4727, 0.4996, 0.0764, 0.3752],
         [0.6759, 0.6067, 0.0910, 0.5282]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
c=torch.rand(226,226,3)
c.unsqueeze(dim=0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
d=torch.range(1,20)
print(d.squeeze(0))
d.squeeze(0).shape

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])


<ipython-input-72-9b18003c67fb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  d=torch.range(1,20)


torch.Size([20])

In [ ]:
d

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])

# Numpy & pytorch

In [ ]:
import numpy as np


In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
#pytorch to numpy
b=a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#numpy to pytorch
torch.from_numpy(b)
type(b)

numpy.ndarray

# AutoGrad

In [ ]:
import torch
x=torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [ ]:
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
#if x is a func of func
x=torch.tensor(3.0,requires_grad=True)
y=x**2
z=torch.sin(y)
print("Value of x:",x)
print("value of y:",y)
print("Value of z:",z)
print(z.backward())
print("Gradient",x.grad)


Value of x: tensor(3., requires_grad=True)
value of y: tensor(9., grad_fn=<PowBackward0>)
Value of z: tensor(0.4121, grad_fn=<SinBackward0>)
None
Gradient tensor(-5.4668)


In [ ]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)


In [ ]:
#forward pass
z=w*x+b
y_pred=torch.sigmoid(z)

In [ ]:
def binary_cross_entropy_loss(y_pred,y):
  loss=-(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred))
  return loss.mean()

In [ ]:
loss=binary_cross_entropy_loss(y_pred,y)
print(loss)

tensor(6.7012, grad_fn=<MeanBackward0>)


In [ ]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [ ]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
y=(x**2).mean()
print(x)
print(y)

tensor([1., 2., 3.], requires_grad=True)
tensor(4.6667, grad_fn=<MeanBackward0>)


In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
#clearing grad
x=torch.tensor(2.0,requires_grad=True)
y=x**2

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(4.)

In [ ]:
x.grad.zero_()
#to make grad zero so that while running same code of line it will no sore the older value as grad and give output accordingly so before every new epoch or iteration we set older one zero

tensor(0.)

In [ ]:
#disable grad-when the model is train and jucst to predict we need disable grad
#and we just need to do run forward pass


#option 1require_grad_(False)
x.requires_grad_(False)

#option 2
z=x.detach()
y=x**2
y1=z**2

y1

tensor(4.)

In [ ]:
#option 3 torch.no_grad()
x=torch.tensor(2.0,requires_grad=True)
with torch.no_grad():
  y=x**2
  print(y)

tensor(4.)
