Write a Python program that creates a TensorFlow constant with the values [100, 200, 300]. Print its shape and data type.

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print(tf.constant([100,200,300]))

tf.Tensor([100 200 300], shape=(3,), dtype=int32)


Write a Python program that implements element-wise addition on two TensorFlow tensors of shape (2, 3) filled with random values

In [4]:
t1=tf.constant(np.random.rand(2,3))
t2=tf.constant(np.random.rand(2,3))
print(t1)
print(t2)

tf.Tensor(
[[0.24313478 0.50579626 0.05900445]
 [0.23249102 0.24944856 0.42336677]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[0.56323117 0.26857592 0.72735406]
 [0.0378298  0.93530665 0.34147737]], shape=(2, 3), dtype=float64)


In [5]:
print(tf.add(t1,t2))

tf.Tensor(
[[0.80636594 0.77437218 0.78635851]
 [0.27032082 1.1847552  0.76484414]], shape=(2, 3), dtype=float64)


Write a Python program to create a TensorFlow tensor of shape (3, 3) filled with zeros and then change its value to nine.

In [6]:
t3=tf.zeros(shape=(3,3),dtype=tf.float32)
print(t3)
t3=tf.constant(9.0,shape=(3,3),dtype=tf.float32)
print(t3)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]], shape=(3, 3), dtype=float32)


Write a Python program that multiplies a TensorFlow tensor by a scalar value and prints the result.


In [7]:
t4=t3*3
print(t4)

tf.Tensor(
[[27. 27. 27.]
 [27. 27. 27.]
 [27. 27. 27.]], shape=(3, 3), dtype=float32)


Write a Python program that uses TensorFlow to compute the dot product of two vectors (1-D tensors).


In [8]:
#tf.multiply" to perform element-wise multiplication of the two vectors and "tf.reduce_sum" to compute the sum of the resulting elements,
#which is the dot product.
t5=tf.multiply(t1,t2)
t5=tf.reduce_sum(t5)
print(t5)

tf.Tensor(0.7023790557294695, shape=(), dtype=float64)


Write a Python program that enables eager execution in TensorFlow 2.x and prints the result of a simple operation without a session.



In [9]:
# the result using result.numpy() without creating a session
t6=t1+t2
print(type(t6))
print(t6.numpy())
print(type(t6))

<class 'tensorflow.python.framework.ops.EagerTensor'>
[[0.80636594 0.77437218 0.78635851]
 [0.27032082 1.1847552  0.76484414]]
<class 'tensorflow.python.framework.ops.EagerTensor'>


Write a Python program that creates a TensorFlow graph and run it inside a session to compute the result of a basic mathematical operation.

In [10]:
graph=tf.Graph()
with graph.as_default():
  a=tf.constant(3.0)
  b=tf.constant(2.0)
  t7=tf.multiply(a,b)

with tf.compat.v1.Session(graph=graph) as session:
  #Create a TensorFlow session (tf.compat.v1.Session())
  #and pass the graph to it.
  t7=session.run(t7)
  print(t7)
print(type(graph))

6.0
<class 'tensorflow.python.framework.ops.Graph'>


 Write a Python program that defines a TensorFlow variable to store a matrix of random values. Initialize and print the variable

In [11]:
m=(3,3)
tm=tf.Variable(tf.random.normal(shape=(3,3)))
#tf.Variable() is used to create a TensorFlow variable
# that can be updated during training.
print(tm.numpy())

[[ 0.04564548 -1.1576623   1.91561   ]
 [ 2.0310555  -1.3116997  -0.09175387]
 [ 1.8443837  -0.22742686  0.5105344 ]]


Write a Python program that explains the difference between TensorFlow variables and constants

In [12]:
tfc=tf.constant([1.0,2.0,3.0])
a=[4.0,5.0,6.0]
tfv=tf.Variable(a)
tfm=tfv.assign([7.0,8.0,9.0])
print(tfc.numpy())
print(tfv.numpy())
print(tfm.numpy())

[1. 2. 3.]
[7. 8. 9.]
[7. 8. 9.]


Write a Python program that creates a TensorFlow constant and a TensorFlow variable. Add, subtract, multiply and divide them and print the result.

In [13]:
ta=tf.constant(21.0)
tb=tf.Variable(3.0)

at=ta+tb
st=ta-tb
dt=ta/tb
mt=ta*tb

print(at.numpy())
print(st.numpy())
print(dt.numpy())
print(mt.numpy())

24.0
18.0
7.0
63.0


 Write a Python program that initializes a TensorFlow variable with an initial value and then updates its value within a loop. Print the variable's value after each update.

In [14]:
x=tf.Variable(100.0,dtype=tf.float32)
up=10
for i in range(up):
  upd=x*2.0
  x.assign(upd)
  print(f"{i+1}:x={x.numpy()}")

1:x=200.0
2:x=400.0
3:x=800.0
4:x=1600.0
5:x=3200.0
6:x=6400.0
7:x=12800.0
8:x=25600.0
9:x=51200.0
10:x=102400.0


Write a Python code to list some common TensorFlow data types available.

In [15]:
d=[tf.float32,tf.float16,tf.float64,tf.int16,tf.int32,tf.int64,tf.bool,tf.complex128,tf.complex64,tf.double,tf.half,tf.bfloat16,tf.int16,
   tf.uint32,tf.resource,tf.uint64,tf.qint16,tf.qint32,tf.qint8,tf.variant,tf.string]

for t in d:
  print(f"{t}:{tf.as_dtype(t).name}")


<dtype: 'float32'>:float32
<dtype: 'float16'>:float16
<dtype: 'float64'>:float64
<dtype: 'int16'>:int16
<dtype: 'int32'>:int32
<dtype: 'int64'>:int64
<dtype: 'bool'>:bool
<dtype: 'complex128'>:complex128
<dtype: 'complex64'>:complex64
<dtype: 'float64'>:float64
<dtype: 'float16'>:float16
<dtype: 'bfloat16'>:bfloat16
<dtype: 'int16'>:int16
<dtype: 'uint32'>:uint32
<dtype: 'resource'>:resource
<dtype: 'uint64'>:uint64
<dtype: 'qint16'>:qint16
<dtype: 'qint32'>:qint32
<dtype: 'qint8'>:qint8
<dtype: 'variant'>:variant
<dtype: 'string'>:string


 Write a Python program that converts a TensorFlow tensor from one data type to another (e.g., from int32 to float64).

In [16]:
tfint32=tf.constant([1,2,3],dtype=tf.int32)
print(tfint32.numpy())
tffloat32=tf.cast(tfint32,dtype=tf.float64)

print(tffloat32.numpy())

[1 2 3]
[1. 2. 3.]


Write a Python program that creates a TensorFlow tensor with a string data type and print its value.

In [17]:
tfs=tf.constant("Tensorflow Practice",dtype=tf.string)
print(tfs.numpy())
print(tfs.numpy().decode())

b'Tensorflow Practice'
Tensorflow Practice


Write a Python program that creates a TensorFlow placeholder for input data of shape (None, 20) where "None" represents a variable batch size.


In [18]:
i_shape=(None,20)
i_d=tf.keras.layers.Input(shape=i_shape,dtype=tf.float32)
print(i_d)

<KerasTensor shape=(None, None, 20), dtype=float32, sparse=False, name=keras_tensor>


Write a Python program that defines a TensorFlow constant tensor containing weights for a neural network layer with shape (10, 4).



In [19]:
w_shape=(10,4)
w=tf.constant(tf.random.normal(w_shape),dtype=tf.float32)
print(w)

tf.Tensor(
[[ 0.69296354  1.0366764  -0.79547924  0.36796963]
 [-0.15263796 -1.4539509  -0.43890208  0.9303918 ]
 [ 1.4040287  -0.07397743 -1.5916362   1.0314986 ]
 [ 1.4181675  -1.9864249  -0.876703    1.4908303 ]
 [ 0.31635898 -1.3762593   0.9624605  -1.1422406 ]
 [-0.41365963  0.7822138   1.3087076   1.6479981 ]
 [ 0.49499786  1.0891067   1.2283872  -1.7132275 ]
 [-1.3703084  -1.7742726   1.456081   -1.4690186 ]
 [-0.29758137  0.18922698  0.3131357  -0.5604081 ]
 [-0.6269119   2.4374099   1.3880157   1.1103224 ]], shape=(10, 4), dtype=float32)


Write a Python program that creates a TensorFlow operation to perform matrix multiplication between two tensors.

In [20]:
tm1=tf.constant([[1,2],[3,4]],dtype=tf.int32)
tm2=tf.constant([[5,6],[7,8]],dtype=tf.int32)

t8=tf.matmul(tm1,tm2)
print(t8)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Write a Python program that builds a feedforward neural network using TensorFlow with one hidden layer and a sigmoid activation function

In [21]:
from tensorflow import keras
input_size=100
hidden_units=32
output=1

model=keras.Sequential([keras.layers.Input(shape=(input_size,)),
                        keras.layers.Dense(units=hidden_units,activation='sigmoid'),
                       keras.layers.Dense(units=output,activation='sigmoid')])
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │         3,232 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,265 (12.75 KB)

 Trainable params: 3,265 (12.75 KB)

 Non-trainable params: 0 (0.00 B)

Write a Python program that creates a custom loss function using TensorFlow that penalizes errors differently for positive and negative examples.

In [22]:
def custom_loss(y_true,y_pred):
  positive_w=3.0
  negative_w=1.0
  loss=-(positive_w*y_true*tf.math.log(y_pred) + negative_w*(1-y_true)*tf.math.log(1-y_pred))
  loss=tf.reduce_mean(loss)
  return loss

Write a Python program that implements a gradient descent optimizer using TensorFlow for a simple linear regression model.

In [26]:
print(np.random.rand(5,2)) #uniform distribution
print(np.random.randn(5,2)) #std normal distribution

[[0.83339031 0.84170698]
 [0.33983411 0.92058912]
 [0.44745356 0.08267983]
 [0.67557722 0.75643351]
 [0.97182116 0.27063876]]
[[ 0.44750651 -0.20830725]
 [-0.55252423  0.29325717]
 [-0.22308103 -1.8317789 ]
 [-0.20787249 -1.99649876]
 [ 1.47240303  0.19945685]]


In [30]:
np.random.seed(0)
x=np.random.rand(100,1)
y=2*x+1+0.1*np.random.randn(100,1)

model=tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(1)
])

loss_fun=tf.keras.losses.MeanSquaredError()
learning_rate=0.01

optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate)
num_epochs=100
for epoch in range(num_epochs):
  with tf.GradientTape() as t:
  #tf.GradientTape() context to record operations
  #for automatic differentiation
    y_pred=model(x)
    loss=loss_fun(y,y_pred)

  gradients=t.gradient(loss,model.trainable_variables)
  optimizer.apply_gradients(zip(gradients,model.trainable_variables))

  print(f"{epoch+1}/{num_epochs},loss:{loss.numpy()}")

final_weights,final_bias=model.layers[0].get_weights()
print(final_weights)
print(final_bias)

1/100,loss:7.842282295227051
2/100,loss:7.479043483734131
3/100,loss:7.133538246154785
4/100,loss:6.804898262023926
5/100,loss:6.4922966957092285
6/100,loss:6.194948673248291
7/100,loss:5.912108898162842
8/100,loss:5.643064975738525
9/100,loss:5.387143135070801
10/100,loss:5.143700122833252
11/100,loss:4.9121246337890625
12/100,loss:4.691836357116699
13/100,loss:4.482282638549805
14/100,loss:4.282937526702881
15/100,loss:4.093301296234131
16/100,loss:3.9128994941711426
17/100,loss:3.741278648376465
18/100,loss:3.578010320663452
19/100,loss:3.422684669494629
20/100,loss:3.2749133110046387
21/100,loss:3.134326219558716
22/100,loss:3.0005719661712646
23/100,loss:2.8733160495758057
24/100,loss:2.752239942550659
25/100,loss:2.637042284011841
26/100,loss:2.5274343490600586
27/100,loss:2.423142671585083
28/100,loss:2.3239073753356934
29/100,loss:2.229480504989624
30/100,loss:2.139626979827881
31/100,loss:2.0541234016418457
32/100,loss:1.9727563858032227
33/100,loss:1.8953235149383545
34/100,l